### ISSUE TITLE
Create editable widget and widget management page

### ISSUE THREAD

**Issue by datnguyen-nfq** [OpenSourceCommerce/log-explorer#108]
Scope: Create editable widget and widget management page. When user access widget dashboard with admin permission. 
so “dashboards” is only a view, the “real” feature is widgets. Admins can create multiple widgets an every widget has the properties:
name
type (pie chart, table, counter…)
a query to select data from one or multiple tables
So in the main navi of log-explorer there will be a feature widgets.
here i can create and modify all widgets
For example, i could have these widgets:
![image](https://user-images.githubusercontent.com/74392945/105317181-7fd8e200-5bf4-11eb-9281-a07791ee3a92.png)
![image](https://user-images.githubusercontent.com/74392945/105317192-823b3c00-5bf4-11eb-84da-da16e996a6fe.png)
![image](https://user-images.githubusercontent.com/74392945/105317199-849d9600-5bf4-11eb-92cf-df0bc776c7cd.png)

Each of these widgets can show data from different tables. this is configured by the data query of the widget.
There is no dependency on widget to table or widget to user. it’s only widget to query. and whatever i put in the query show data in the widget.
Also the widget does not belong to a user. Admin can create widgets which are visible for all users (edited) 
Now the dashboard is only a view to be able to see more than one widget on the same page. so Admins can create a dashboard called “marketing” and this shows widget #1 and widget #2. (edited) 
Then there could be a dashboard with the name “devops” and this shows widget #3, #2 and #4 (edited) 
There is also no dependency between user, table and dashboard. Only between dashboard and widgets. Each dashboard can show any number of widgets.
Dashboard also don’t belong to a user. Admin will create them and they are visible for very user.

**Comment by phucnh-nfq** [comment]
@ThomasLohner I'm confusing about 

> Each of these widgets can show data from different tables. this is configured by the data query of the widget.
> There is no dependency on widget to table

If widget do not have relationship with table and column of table that mean admin need to write full query for it like:

> SELECT status, COUNT() AS c FROM nginx_access WHERE ....
> SELECT ip, COUNT() AS total FROM nginx_access WHERE ....

And event like

> SELECT * FROM nginx_access WHERE ...

So we do not know the structure of data output and it very hard to control the query results to implement it.


In my opinion 1 widget has only 1 table and 1 column name (sample status, ip, URL...), User can add additional query to limit the results but can not control the SELECT column and FROM table at query.
Sample:

> Widget 1: name: Status, table: nginx_access, column: status, condition: status > 500
> Widget 2: name: IP, table: nginx_access, column: ip, condition: status <= 300 AND ...

Or maybe I miss-understand about your ideal about there widgets?

**Comment by datnguyen-nfq** [comment]
You can check this feature in Original Branch. Thanks!
