### ISSUE TITLE
Improve clickhouse query performance

### ISSUE THREAD

**Issue by ThomasLohner** [OpenSourceCommerce/log-explorer#117]
Query performance is not good on a dataset with 1 billion rows or more. This needs to be fixed.

###  Our current approach
We are trying to avoid sorting data in clickhouse because this needs too much memory on huge datasets. Since the data is inserted with a timestamp it basically is already sorted. So we can `SELECT` without sorting. Only problem is, in the frontend we need the latest data first, not the oldest.

What we basically do is:

1. Count number of rows between given timestamps
```
SELECT COUNT() FROM nginx_access WHERE timestamp >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-22 21:20:51'

┌───COUNT()─┐
│ 140082034 │
└───────────┘
```

2. Get data in inserted order but skip the first xxx records, so we only get the newest rows
```
SELECT <fields> FROM nginx_access WHERE >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-23 07:20:51' LIMIT 140081934, 100
```

This approach works good for small datasets, but is very slow on huge tables. Also i found out that clickhouse seems to scan all selected columns **before** the `LIMIT` takes place:

With only a few columns it works quite well
```
SELECT timestamp, status FROM nginx_access WHERE timestamp >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-23 07:20:51' LIMIT 140081934, 100

100 rows in set. Elapsed: 0.117 sec. Processed 140.13 million rows, 840.79 MB (1.20 billion rows/s., 7.17 GB/s.)
```

The more columns you select, the longer it takes
```
SELECT timestamp, status, url, referer, user_agent, host FROM nginx_access WHERE timestamp >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-23 07:20:51' LIMIT 140081934, 100

100 rows in set. Elapsed: 2.937 sec. Processed 140.13 million rows, 39.28 GB (47.71 million rows/s., 13.37 GB/s.)
```

At some point it gets very slow
```
SELECT * FROM nginx_access WHERE timestamp >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-23 07:20:51' LIMIT 140081934, 100

100 rows in set. Elapsed: 15.406 sec. Processed 140.13 million rows, 109.71 GB (9.10 million rows/s., 7.12 GB/s.)
```

### New idea: Sorting data in clickhouse
Sorting rows by `timestamp DESC` in clickhouse is much faster compared to `LIMIT xxx, 100`:
```
SELECT * FROM nginx_access WHERE timestamp >= '2021-03-22 07:20:51' AND timestamp <= '2021-03-23 07:20:51' ORDER BY timestamp DESC LIMIT 100

100 rows in set. Elapsed: 1.124 sec. Processed 2.67 million rows, 2.07 GB (2.38 million rows/s., 1.84 GB/s.)
```

However, we still have the same problem like above. Clickhouse **scans all columns before** `LIMIT` takes places and will hit memory limits pretty quickly:
```
SELECT * FROM nginx_access WHERE timestamp >= '2021-03-21 07:20:51' AND timestamp <= '2021-03-24 07:20:51' ORDER BY timestamp DESC LIMIT 100

Received exception from server (version 20.12.5):
Code: 241. DB::Exception: Received from 10.0.2.6:9000. DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 4237024 bytes), maximum: 9.31 GiB: While executing MergingSortedTransform.
```

### Solution: Find out exactly which rows need to be selected
We need a two-step process:
1. Find **which** rows match the given timestamp and all other `WHERE` conditions
2. Select all needed columns **only** from there rows

If we implement an `_id` column, we can use sorting in clickhouse without wasting to much memory on scanning all columns of the table:
```
SELECT _id FROM nginx_access WHERE timestamp >= '2021-03-21 07:20:51' AND timestamp <= '2021-03-24 07:20:51' ORDER BY timestamp DESC LIMIT 100

100 rows in set. Elapsed: 0.192 sec. Processed 8.71 million rows, 174.11 MB (45.25 million rows/s., 905.06 MB/s.)
```

And then `SELECT` all needed colounms for these rows:
```
SELECT <columns> FROM nginx_access WHERE _id IN (...)
```

**Since clickhouse supports sub-queries this can all be dome with one single query:**
```
SELECT * FROM nginx_access WHERE _id IN (SELECT _id FROM nginx_access WHERE timestamp >= '2021-03-21 07:20:51' AND timestamp <= '2021-03-24 07:20:51' ORDER BY timestamp DESC LIMIT 100)

100 rows in set. Elapsed: 1.755 sec. Processed 451.98 million rows, 7.23 GB (257.58 million rows/s., 4.12 GB/s.)
```

Still not perfect, but less than 2 seconds is pretty good for 450 mio rows.

### TODO
* every tables needs a column `_id` with an index. There is no auto increment in clickhouse, but we can use `uuid`
```
    `_id` UUID,
    INDEX _id _id TYPE bloom_filter GRANULARITY 512
```
* in API check if there is a valid uuid in `_id`. If not add this to the `INSERT` statement
```
INSERT INTO [db.]table (_id, ...) VALUES (generateUUIDv4(), ...)
```
* change commands for sample data

**Comment by phucnh-nfq** [comment]
@ThomasLohner 

> INDEX _id _id TYPE bloom_filter GRANULARITY 512

`bloom_filter` does not support for `UUID` (https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#available-types-of-indices)

How about we store `_id` as `String` or use `_id` as `primary key`?

> ORDER BY (timestamp, _id)

**Comment by ThomasLohner** [comment]
All of the queries are based on timestamp. I think if this is not the primary key it will hurt performance. According to this uuid is supported: https://github.com/ClickHouse/ClickHouse/pull/16642

I can create the index but i'm not sure how to debug queries and see if the index is being used or not. I think we need to learn how to profile queries.
