### ISSUE TITLE
Save filter into cookie 

### ISSUE THREAD

**Issue by datnguyen-nfq** [OpenSourceCommerce/log-explorer#118]
Expect: When user filter in dashboard. Filter information have to save into cookie.

Current: Lost filter information after user back to dashboard page

**Comment by datnguyen-nfq** [comment]
Hi @ThomasLohner Do you think we should save Date range picker to cookie ? 
![Screen Shot 2021-03-31 at 11 47 19](https://user-images.githubusercontent.com/74392945/113091799-e55dd600-9216-11eb-90bc-2bbf24c31505.png)

**Comment by ThomasLohner** [comment]
Yes. Currently "1 hours", "12 hours" etc. is already stored in between page reloads. The same should be done for custom dates and "realtime"
