### ISSUE TITLE
Need of console command to create pre-defined tables

### ISSUE THREAD

**Issue by SirUrban** [OpenSourceCommerce/log-explorer#130]
As we want to be able to automatically install log-explorer in our customer projects we do need a console command to create the needed tables. Parameters should be:
- table name
- list of key-value pairs for the fields.

Example:
```
./bin/console app:createtable -n apache_access --fields=status:Int16,method:String,size:Int16,size:Int16,referrer:String
```

The format of the params may be changed - choose what fits best for you.
This should work the same way as if you create a table in log-explorer UI. May be you need additional params like lifetime?

**Comment by nhatdo-nfq** [comment]
### Description:
  Create new table.

  **Example** 
`php bin/console app:createtable apache_access -f status:Int16 -f method:String -f size:Int16 -f referer:String -f createdAt:DateTime --ttl='timestamp:3:MONTH'`

### Usage:
  app:createtable [options] [--] [<name>]

**Arguments:**
  name                  Table name

**Options:**
  -f, --fields=FIELDS   Table column. status:Int16 (multiple values allowed)
  -t, --ttl[=TTL]       Time to life {column_name}:{interval}:{type}
                        Ex: timestamp:3:month -> "TTL timestamp + INTERVAL 3 MONTH"

**Comment by SirUrban** [comment]
@nhatdo-nfq Can you please add the content of your last comment to the README file?
