### ISSUE TITLE
Make explore view more compact

### ISSUE THREAD

**Issue by SirUrban** [OpenSourceCommerce/log-explorer#135]
We want to see more information at once in explore view. So please make the view more compact, by:
- reducing font size (e. g. 0.8 em)
- reducing line height to 0.7
- make column width flexible and regarding the content (e. g. column "status" can be much smaller as column "referrer")

Remove the "collapse" function (the minus sign "-" in the upper right corner).

The left area with the main menu items should be a bit smaller (180px). Remove the "Scale.sc" text on the top of this area. We should think about a nice logo for log-explorer - may be you have some ideas? ;-) 

Please make also the log row details view (popup) more compact and smaller.

**Comment by SirUrban** [comment]
The view is much better now but still needs a bit of improvement:
The column width should be more flexible. Look at this screenshot:

![image](https://user-images.githubusercontent.com/1540259/123433560-e1e6aa80-d5cb-11eb-8915-e740d5f7f2b4.png)

The first column "host" contains strings like: "app1", "app2", "master". But only the first character is visible. I know it's a bit tricky to find the right way here ... - please think about this and make suggestions.
Would it be a solution to make the columns configurable in database settings? What I mean is another field here:

![image](https://user-images.githubusercontent.com/1540259/123434611-f8413600-d5cc-11eb-882c-b91f1cecf4a1.png)

so that you can set a width param per column? I'm not sure if this is the best solution ... - so you may help with different ideas.

**Comment by nhatdo-nfq** [comment]
To set the column width, please go to table setting modal
![image](https://user-images.githubusercontent.com/60637966/123781314-496b6580-d8fe-11eb-9370-74bce031d379.png)
![image](https://user-images.githubusercontent.com/60637966/123781389-6142e980-d8fe-11eb-81c9-201a13a79445.png)
