### ISSUE TITLE
Make searches storable

### ISSUE THREAD

**Issue by SirUrban** [OpenSourceCommerce/log-explorer#155]
In log-explorer you can do searches by simple sql-queries. Please add the feature to store such searches. So add a button "save search" under the search field. If button is clicked, show popup with a field "search title" where user can add a title for the stored search query. Also show the query in an editable field so user can modify if he wants.

At the bottom of the popup show a button "save" or "abort".
If the search is saved, the title should be added to a dropdown "saved searches". This dropdown should be shown beside the button "save search" with a title "saved searches". Entries should be sorted alphabetically.

If a saved search is selected from the dropdown the search should be executed immediately.

**Comment by SirUrban** [comment]
I re-opened this because of course we also need the possibility to delete stored searches. So please implement a delete icon into the list of stored searches (in the dropdown beside the edit icon).

**Comment by phucnh-nfq** [comment]
I just also updated save query by user. so migration will delete all old saved query.
