### ISSUE TITLE
Export of logs

### ISSUE THREAD

**Issue by SirUrban** [OpenSourceCommerce/log-explorer#156]
We do want to have the possibility to export a log view. So if you have filtered logs by some sql query and limited it to a certain time range there should be a button "export". If you click on this button you will see a popup with a choice of export format. For now we will show only "csv" and "json" as options. There might be some more in future.

If the format is chosen you can click a button "export and download" and the export will be done and a will be downloaded. The name of the file should be the table name (e. g. "apache_access") plus an actual timestamp (e. g. 2021-07-21_14:59:34) plus the extension (".json" or ".csv").

The size of exported logfiles is not restricted in any way. The export should be executed asynchron which means: If a user triggers an export this will be queued and a message appears: "Your export is being prepared and will be available soon in the download section." The "download" section has to be a new item in the left menu. Clicking on this item will show a page with a list of available downloads ordered by date of creation. Files in the download section will be available for 7 days. A daily cleanup job will delete all files older than 7 days. This has to be shown as a message on the download page: "Files will be available for 7 days only."
The download must only be available for logged in users.

**Comment by phucnh-nfq** [comment]
@SirUrban I have an ideal about it. How about if we define a limitation call NUMBER. First we already knew how many rows we will export so we can check if it smaller than a NUMBER we allowed to export directly. If the number of rows is bigger than that NUMBER we show an alert to user we will export in background and send the download link to user email.

**Comment by nhatdo-nfq** [comment]
### Documentation
Console command docs: [click here](https://github.com/OpenSourceCommerce/log-explorer/blob/master/docs/command/logview-export.md)

### Usage
To export data, click on Logview table menu -> Export
![image](https://user-images.githubusercontent.com/60637966/128310415-c5a1b55d-327c-433c-ba0e-378ec350dcb9.png)
