### ISSUE TITLE
Creating Alerts

### ISSUE THREAD

**Issue by SirUrban** [OpenSourceCommerce/log-explorer#158]
We want to have a feature that allows the user to configure specific searches and thresholds to trigger alerts.

So please implement a new item in the main left menu which is called "Alerts". The page behind this should show a list of already configured alerts (if there are some) and a button "create new alert". 
Clicking the create-button shows a form with following components:
- a field for the title of the alert - title: "name of alert"
- a dropdown with all available tables - title: "select table"
- a field for a WHERE-clause (SQL) to specify the query - title: criteria to search for in sql mode
- a filed for the threshold value (integer) - title: "limit for alert"
- a time range selector (like in the other views: 1 hour, 12 hours .... custom range) - title: time range
- a field for the interval of checks which allows only integers - title: "check interval in minutes"
- a field for email address which will receive the alert mail - title: email address
- a field for the subject of the email - title: email subject
- a checkbox: "active"
- a button: "save alert"

If the alert is saved user is redirected to the main page with a list of all configured alerts. Each alert in the list can be edited or deleted (show some symbols like in user list).

The resulting query of a configured alert will be executed all X minutes (X = the configured interval). It will always be a "SELECT COUNT(*) ..." query with following structure:

SELECT COUNT(*) FROM [selected table from dropdown] WHERE [configured where-clause] AND timestamp BETWEEN [selected time range]

The result will be compared to the configured limit. If it's above an email will be triggered containing the title of the alert and the result of the query like this: "ATTENTION: Your alert [TITLE] has been triggered at [timestamp]. The limit of [configured limit] has been reached - actual value is: [query result].

Example:
- Title of alert: "PHP Fatal errors per hour"
- Selected table: "apache_error"
- WHERE-clause: "errormsg LIKE '%Fatal%'"
- Limit for alert: 5
- Time range: 60
- Interval: 60
- Email address: "bla@foo.com"
- Email subject: "Log-Explorer Alert: PHP Fatal errors per hour"

Resulting query:
SELECT COUNT(*) FROM apache_error WHERE errormsg LIKE '%Fatal%' AND timestamp BETWEEN NOW() AND NOW - 1 hour (not sure how this is done correctly - but you will find out! ;-) )

This query has to be triggered each 60 minutes and as soon as the result is greater than 5 the email has to be sent.
We probably have to discuss how the regular execution of these queries can be done. Cronjobs? Some other idea? Please think about and make suggestions.

**Comment by nhatdo-nfq** [comment]
@SirUrban Hi Andy, about how the regular execution of these queries, i have opinion:
- Firstly, we will execute the queries every minute
- Log the result to a table
- Check the last log:
   + if the last log result is greater than the limit and has sent the alert mail => next runt will be executed after the interval
   + if the last log result is less than the limit => continue to execute every minute

**Comment by SirUrban** [comment]
@nhatdo-nfq Sounds good for me. Let's try it this way. May be we have to collect some experience and modify it later.

**Comment by phucnh-nfq** [comment]
@SirUrban for time range you expected using a `a time range selector (like in the other views: 1 hour, 12 hours .... custom range) - title: time range`
it good UI and eazy for user to select but I think no one need a alert for 
Yesterday, Last month, or Custom range ... so in my opinion, just an input tag for input hours or minutes is more flexible.
