### ISSUE TITLE
Keep state of "realtime" between pageviews

### ISSUE THREAD

**Issue by ThomasLohner** [OpenSourceCommerce/log-explorer#97]
Changing the date range or reloading the page enables realtime. If the user disabled realtime it should stay disabled.

**Comment by ThomasLohner** [comment]
It now keeps the state of `real time` when changing the date range. But it does not work on page reload. When the user reloads the page it switches `real time` to on and also resets the date range. Both values should be kept when reloading the page.

**Comment by phucnh-nfq** [comment]
save date range will be implement in #118
